config/routes.rb
Rails.application.routes.draw do
  resources :products
  resources :comments
  resources :posts
  
  root to: "home#indexVisit"

  get 'home/indexVisit'
  get 'home/indexUser'
  get 'home/market'
  get 'home/about'
  
  

  devise_for :admins

  devise_for :users, controllers: {
    sessions: 'users/sessions',
    passwords: 'users/passwords',
    registrations: 'users/registrations',
    omniauth_callbacks: 'users/omniauth_callbacks'
  }

  devise_for :veterinaries, controllers: {
    sessions: 'veterinaries/sessions',
    passwords: 'veterinaries/passwords',
    registrations: 'veterinaries/registrations'
  }

  resource :cart, only: [:show, :update, :destroy] do
    member do
      post :pay_with_paypal
      get :process_paypal_payment
    end
  end


end

app/views/shared/_footer.html.erb
<!-- Footer -->
<footer class="bg-info text-center text-white">
    <!-- Grid container -->
    <div class="container p-4">
      <!-- Section: Social media -->
      <section class="mb-4">
        <!-- Facebook -->
        <a class="btn btn-outline-light btn-floating m-1" href="#!" role="button"
          ><i class="fab fa-facebook-f"></i
        ></a>
  
        <!-- Twitter -->
        <a class="btn btn-outline-light btn-floating m-1" href="#!" role="button"
          ><i class="fab fa-twitter"></i
        ></a>
  
        <!-- Google -->
        <a class="btn btn-outline-light btn-floating m-1" href="#!" role="button"
          ><i class="fab fa-google"></i
        ></a>
  
        <!-- Instagram -->
        <a class="btn btn-outline-light btn-floating m-1" href="#!" role="button"
          ><i class="fab fa-instagram"></i
        ></a>
  
        <!-- Linkedin -->
        <a class="btn btn-outline-light btn-floating m-1" href="#!" role="button"
          ><i class="fab fa-linkedin-in"></i
        ></a>
  
        <!-- Github -->
        <a class="btn btn-outline-light btn-floating m-1" href="#!" role="button"
          ><i class="fab fa-github"></i
        ></a>
      </section>
      <!-- Section: Social media -->
  
      <!-- Section: Form -->
      <section class="">
        <form action="">
          <!--Grid row-->
          <div class="row d-flex justify-content-center">
            <!--Grid column-->
            <div class="col-auto">
              <p class="pt-2">
                <strong>Sign up for our newsletter</strong>
              </p>
            </div>
            <!--Grid column-->
  
            <!--Grid column-->
            <div class="col-md-5 col-12">
              <!-- Email input -->
              <div class="form-outline form-white mb-4">
                <input type="email" id="form5Example21" class="form-control" />
                <label class="form-label" for="form5Example21">Email address</label>
              </div>
            </div>
            <!--Grid column-->
  
            <!--Grid column-->
            <div class="col-auto">
              <!-- Submit button -->
              <button type="submit" class="btn btn-outline-light mb-4">
                Subscribe
              </button>
            </div>
            <!--Grid column-->
          </div>
          <!--Grid row-->
        </form>
      </section>
      <!-- Section: Form -->
  
      <!-- Section: Text -->
      <section class="mb-4">
        <p>
            DESCARGA NUESTRA APP PARA
        </p>
      </section>
      <!-- Section: Text -->
  
      <!-- Section: Links -->
      <section class="">
        <!--Grid row-->
        <div class="row">
          <!--Grid column-->
          <div class="col-lg-3 col-md-6 mb-4 mb-md-0">
  
            <ul class="list-unstyled mb-0">
              <li>
                <a class="btn btn-outline-light btn-floating m-1" href="#!" role="button"><i class="fab fa-windows"></i></i></a>
              </li>
            </ul>
          </div>
          <!--Grid column-->
  
          <!--Grid column-->
          <div class="col-lg-3 col-md-6 mb-4 mb-md-0">
            <ul class="list-unstyled mb-0">
              <li>
                <a class="btn btn-outline-light btn-floating m-1" href="#!" role="button"><i class="fab fa-android"></i></i></a>
              </li>
            </ul>
          </div>
          <!--Grid column-->
  
          <!--Grid column-->
          <div class="col-lg-3 col-md-6 mb-4 mb-md-0">
  
            <ul class="list-unstyled mb-0">
              <li>
                <a class="btn btn-outline-light btn-floating m-1" href="#!" role="button"><i class="fab fa-apple"></i>  </i></a>
              </li>
            </ul>
          </div>
          <!--Grid column-->
  
          <!--Grid column-->
          <div class="col-lg-3 col-md-6 mb-4 mb-md-0">
  
            <ul class="list-unstyled mb-0">
              <li>
                <a class="btn btn-outline-light btn-floating m-1" href="#!" role="button"><i class="fab fa-google-play"></i></i></a>
              </li>
            </ul>
          </div>
          <!--Grid column-->
        </div>
        <!--Grid row-->
      </section>
      <!-- Section: Links -->
    </div>
    <!-- Grid container -->
  
    <!-- Copyright -->
    <div class="text-center p-3" style="background-color: rgba(0, 0, 0, 0.2);">
      © 2022 Copyright:
      <a class="text-white" href="https://www.github.com/cratulas">MM</a>
    </div>
    <!-- Copyright -->
  </footer>
  <!-- Footer -->

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-info">
    <% if user_signed_in? %>

        <%= link_to image_tag('LOGO3.png', :size => "71x82" ), home_indexUser_path, class: "navbar-brand mx-4"%>

        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavDropdown">
        <ul class="navbar-nav mx-auto">
        <li class="nav-item active">
            <%= link_to 'Community', posts_path, class: "nav-link mx-4 text-light" %><span class="sr-only">(current)</span></a>
        </li>
        <li class="nav-item active">
            <%= link_to 'MarketPlace', home_market_path, class: "nav-link mx-4 text-light" %>
        </li>

        <li class="nav-item active">
            <%= link_to 'About', home_about_path, class: "nav-link mx-4 text-light" %>
        </li>

        <li class="nav-item active">
            <%= link_to 'Appoinment', home_indexUser_path, class: "appoinment nav-link mx-4 text-light bg-warning" %>
        </li>

        <li class="nav-item dropdown mx-auto">
        <a class="nav-link dropdown-toggle active text-light" href="#" id="navbarDropdownMenuLink" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            My Perfil
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
            <%= link_to 'Edit', edit_user_registration_path, class: "dropdown-item " %>
            <%= link_to 'Logout', destroy_user_session_path, :method => :delete , class: "dropdown-item " %>        
        </div>
        </li>
        </ul>
   
        <%= link_to '<i class="fas fa-cart-plus fa-2x"></i>'.html_safe, cart_path, class: "nav-link mx-4" %>


    <% else %>
        
        <%= link_to image_tag('LOGO3.png', :size => "71x82" ), root_path, class: "navbar-brand mx-4"%>

        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavDropdown">
        <ul class="navbar-nav mx-auto">
        <li class="nav-item active">
            <%= link_to 'Community', posts_path, class: "nav-link mx-4 text-light" %><span class="sr-only">(current)</span></a>
        </li>
        <li class="nav-item active">
            <%= link_to 'MarketPlace', home_market_path, class: "nav-link mx-4 text-light" %>
        </li>

        <li class="nav-item active">
            <%= link_to 'About', home_about_path, class: "nav-link mx-4 text-light" %>
        </li>

        <li class="nav-item active">
            <%= link_to 'Appoinment', home_indexVisit_path, class: "appoinment nav-link mx-4 text-light bg-warning" %>
        </li>
        
        <%= link_to image_tag('paw.png', :size => "49x60" ), root_path, class: "navbar-brand ml-5 "%>
    </ul>
    </div>
    <% end %>


</nav>