config/routes.rb
Rails.application.routes.draw do
  resources :products
  resources :comments
  resources :posts
  
  root to: "home#indexVisit"

  get 'home/indexVisit'
  get 'home/indexUser'
  get 'home/market'
  get 'home/about'
  
  

  devise_for :admins

  devise_for :users, controllers: {
    sessions: 'users/sessions',
    passwords: 'users/passwords',
    registrations: 'users/registrations',
    omniauth_callbacks: 'users/omniauth_callbacks'
  }

  devise_for :veterinaries, controllers: {
    sessions: 'veterinaries/sessions',
    passwords: 'veterinaries/passwords',
    registrations: 'veterinaries/registrations'
  }

  resource :cart, only: [:show, :update, :destroy] do
    member do
      post :pay_with_paypal
      get :process_paypal_payment
    end
  end


end

app/models/post.rb
class Post < ApplicationRecord
  has_many :comments, dependent: :destroy
  belongs_to :user
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: %i[ show edit update destroy ]
  before_action :authenticate_user!
  # GET /posts or /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1 or /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts or /posts.json
  def create
    @post = Post.new(post_params.merge(user: current_user))

    respond_to do |format|
      if @post.save
        UserMailer.new_post(current_user, @post).deliver_later
        format.html { redirect_to root_path, notice: "Post was successfully created." }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end


  # PATCH/PUT /posts/1 or /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to post_url(@post), notice: "Post was successfully updated." }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1 or /posts/1.json
  def destroy
    @post.destroy

    respond_to do |format|
      format.html { redirect_to posts_url, notice: "Post was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def post_params
      params.require(:post).permit(:content, :user_id)
    end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_form.html.erb
<%= form_with(model: post, local: true) do |form| %>
  <% if post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :content %>
    <%= form.text_area :content %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<p id="notice"><%= notice %></p>

<div class="container-fluid">

      <h1 class="text-center my-3">THE WALL</h1>
      <% @posts.each do |post| %>
      <div class="row">
        <div class="col-sm my-2 mx-0 mx-0">

        </div>

        <div class="col-sm card my-2">

          
          <div class="container p-4">
            <div class="row">
              <div class="col-sm">
                <% if post.user.photo.attached? %>
                <div class="tweet-img">
                  <%= image_tag post.user.photo.variant(resize:  "100x100", colorspace: "gray"), class: 'rounded img-responsive mb-4', alt: "Not conexion"%>
                  <li class="no-bullets"><%= link_to 'Add Comment', new_comment_path(id_post: post.id), class: "btn btn-success mt-3" %></li>
                  <% if current_user.id == post.user_id %>
                  <li class="no-bullets"><%= link_to 'Edit', edit_post_path(post) , class: "btn btn-warning mt-3" %></li>
                  <li class="no-bullets"><%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } , class: "btn btn-danger mt-3" %></li>
                  <% end %> 
                </div>
                <% else %>
                <div class="tweet-img">
                  <%= image_tag("COMUNIDAD.png", size: "100x100", alt: "Edit Entry" ,class: "my-3")%>
                  <li class="no-bullets"><%= link_to 'Add Comment', new_comment_path(id_post: post.id), class: "btn btn-success mt-3" %></li>
                  <% if current_user.id == post.user_id %>
                  <li class="no-bullets"><%= link_to 'Edit', edit_post_path(post) , class: "btn btn-warning mt-3" %></li>
                  <li class="no-bullets"><%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } , class: "btn btn-danger mt-3" %></li>
                  <% end %> 
                </div>

                
                <% end %>
              </div>
              <div class="col-sm">
                <%= post.content %>
                <% if post.comments.exists?%>
                  <li class="no-bullets"><%= link_to 'View Comments', post, class: "btn btn-info mt-3" %></li>
                <% end %> 
              </div>
              
            </div>
          </div>
        </div>       


        <div class="col-sm my-2 text-right mx-0 p-0">

        </div>
        
      </div>
      <% end %>
      <p class="text-center"><%= link_to 'New Post', new_post_path, class: " my-4 btn btn-primary"%></p>
      
</div>

app/views/posts/new.html.erb
<div class= "container-fluid newpost">    

<div class= "container">    
<h1>New Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Back', posts_path %>
</div>
</div>

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>


<div class="container-fluid">

      <h1 class="text-center my-3">COMMENTS</h1>
      <% @post.comments.each do |comment| %>
      <div class="row">
        <div class="col-sm my-2 mx-0 mx-0">

        </div>

        <div class="col-sm card my-2">

          
          <div class="container p-4">
            <div class="row">
              <div class="col-sm">
                <% if @post.user.photo.attached? %>
                <div class="tweet-img">
                  <%= image_tag comment.user.photo.variant(resize:  "100x100", colorspace: "gray"), class: 'rounded img-responsive mb-4'%>
                                 <% if current_user.id == comment.user_id %>
                <li class="no-bullets"><%= link_to 'Show', comment, class: "btn btn-success mt-3" %></li>
                <li class="no-bullets"><%= link_to 'Edit', edit_comment_path(comment), class: "btn btn-warning mt-3" %></li>
                <li class="no-bullets"><%= link_to 'Destroy', comment, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger mt-3" %></li>
                <% end %>
                </div>
                <% else %>
                 <div class="tweet-img">
                  <%= image_tag("COMUNIDAD.png", size: "100x100", alt: "Edit Entry" ,class: "my-3")%>
                </div>
                <% end %>
              </div>
              <div class="col-sm">
                <%= comment.content %>
 
              </div>
              
            </div>
          </div>
        </div>       


        <div class="col-sm my-2 text-right mx-0 p-0">

        </div>
        
      </div>
      <% end %>

      <p class="text-center"><%= link_to 'Back', posts_path, class: " my-4 btn btn-primary"%></p>
</div>

      